// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Db is an autogenerated mock type for the Db type
type Db struct {
	mock.Mock
}

// SetEmail provides a mock function with given fields: ctx, email, isActive
func (_m *Db) SetEmail(ctx context.Context, email string, isActive bool) error {
	ret := _m.Called(ctx, email, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, email, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDb creates a new instance of Db. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDb(t interface {
	mock.TestingT
	Cleanup(func())
}) *Db {
	mock := &Db{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
