version: '3.8'

services:
  api:
    restart: always
    env_file:
      - ./currency-rates/.env
    build:
      context: ./currency-rates
    ports:
      - "8183:8183"
    depends_on:
      admin-db:
        condition: service_healthy  
      nats:
        condition: service_healthy

  subscriber:
    restart: always
    env_file:
      - ./subscription-sender/.env
    build:
      context: ./subscription-sender
    ports:
      - "8184:8184"    
    depends_on:
      nats:
        condition: service_healthy    
    healthcheck:
      test: wget http://localhost:8184/health -q -S -O -
      interval: 10s
      timeout: 5s
      retries: 3       

  admin-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "7632:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.10.16-alpine3.19
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_LOG_NAME=nats-server
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      interval: 10s
      timeout: 5s
      retries: 3
  