version: '3.8'

services:
  admin-db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: 'test_user'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'api_template'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "8632:5432"
    volumes:
      - ./currency-rates/sql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5