name: Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "currency-rates/go.mod"
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.0
          args: --timeout 5m
          working-directory: currency-rates/

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "currency-rates/go.mod"
          check-latest: true
          
      - name: Tests
        working-directory: currency-rates/
        run: go test -v ./...

      - name: Arch-go
        run: go install -v github.com/fdaines/arch-go@latest

      - name: Run arch test
        working-directory: currency-rates/
        run: arch-go -v  
        
  integration-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "currency-rates/go.mod"
          check-latest: true

      - name: Run Docker container
        run: docker-compose  -f docker-compose.test.yaml up --build -d

      - name: Wait for postgress
        run: |
          for i in {1..10}; do
            if nc -zv localhost 8632; then
              echo "Service is up!"
              exit 0
            fi
            echo "Waiting for service to be available..."
            sleep 10
          done
          echo "Service did not become available in time"
          exit 1
          
      - name: Integration Tests
        working-directory: currency-rates/
        run: go test -v -tags=integration ./...    

      - name: Down Docker container
        run: docker-compose  -f docker-compose.test.yaml down
